<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<parent>
        <groupId>io.wangk.peekaboo</groupId>
        <artifactId>tis</artifactId>
        <version>1.0.0</version>
	</parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>application-webadmin</artifactId>
    <version>1.0.0</version>
    <name>application-webadmin</name>
    <packaging>jar</packaging>

	<dependencies>
		<!-- 业务组件依赖 -->
        <dependency>
            <groupId>io.wangk.peekaboo</groupId>
            <artifactId>common-satoken</artifactId>
            <version>1.0.0</version>
        </dependency>
        <dependency>
            <groupId>io.wangk.peekaboo</groupId>
            <artifactId>common-ext</artifactId>
            <version>1.0.0</version>
        </dependency>
        <dependency>
            <groupId>io.wangk.peekaboo</groupId>
            <artifactId>common-redis</artifactId>
            <version>1.0.0</version>
        </dependency>
        <dependency>
            <groupId>io.wangk.peekaboo</groupId>
            <artifactId>common-mobile</artifactId>
            <version>1.0.0</version>
        </dependency>
        <dependency>
            <groupId>io.wangk.peekaboo</groupId>
            <artifactId>common-report</artifactId>
            <version>1.0.0</version>
        </dependency>
        <dependency>
            <groupId>io.wangk.peekaboo</groupId>
            <artifactId>common-online</artifactId>
            <version>1.0.0</version>
        </dependency>
        <dependency>
            <groupId>io.wangk.peekaboo</groupId>
            <artifactId>common-flow-online</artifactId>
            <version>1.0.0</version>
        </dependency>
        <dependency>
            <groupId>io.wangk.peekaboo</groupId>
            <artifactId>common-log</artifactId>
            <version>1.0.0</version>
        </dependency>
        <dependency>
            <groupId>io.wangk.peekaboo</groupId>
            <artifactId>common-minio</artifactId>
            <version>1.0.0</version>
        </dependency>
        <dependency>
            <groupId>io.wangk.peekaboo</groupId>
            <artifactId>common-sequence</artifactId>
            <version>1.0.0</version>
        </dependency>
        <dependency>
            <groupId>io.wangk.peekaboo</groupId>
            <artifactId>common-datafilter</artifactId>
            <version>1.0.0</version>
        </dependency>
        <dependency>
            <groupId>io.wangk.peekaboo</groupId>
            <artifactId>common-swagger</artifactId>
            <version>1.0.0</version>
        </dependency>
        <dependency>
            <groupId>io.wangk.peekaboo</groupId>
            <artifactId>common-social</artifactId>
            <version>1.0.0</version>
        </dependency>
        <dependency>
            <groupId>io.wangk.peekaboo</groupId>
            <artifactId>common-dict</artifactId>
            <version>1.0.0</version>
        </dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
                <version>${spring-boot.version}</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>repackage</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
		</plugins>
	</build>

    <profiles>
        <profile>
            <id>release</id>
            <activation>
                <activeByDefault>false</activeByDefault>
            </activation>
            <build>
                <finalName>tis-${project.version}</finalName>
                <plugins>
                    <plugin>
                        <groupId>com.github.eirslett</groupId>
                        <artifactId>frontend-maven-plugin</artifactId>
                        <version>1.15.0</version>
                        <configuration>
                            <workingDirectory>${project.basedir}/../ui</workingDirectory>
                        </configuration>
                        <executions>
                            <execution>
                                <id>install node and npm</id>
                                <goals>
                                    <goal>install-node-and-npm</goal>
                                </goals>
                                <configuration>
                                    <nodeVersion>v22.2.0</nodeVersion>
                                    <npmVersion>10.7.0</npmVersion>
                                </configuration>
                            </execution>
                            <execution>
                                <id>clean</id>
                                <goals>
                                    <goal>npm</goal>
                                </goals>
                                <configuration>
                                    <arguments>cache clean --force</arguments>
                                </configuration>
                            </execution>
                            <execution>
                                <id>install</id>
                                <goals>
                                    <goal>npm</goal>
                                </goals>
                                <phase>generate-resources</phase>
                                <configuration>
                                    <arguments>install</arguments>
                                </configuration>
                            </execution>
                            <execution>
                                <id>build</id>
                                <goals>
                                    <goal>npm</goal>
                                </goals>
                                <configuration>
                                    <arguments>run build</arguments>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                    <plugin>
                        <artifactId>maven-clean-plugin</artifactId>
                        <configuration>
                            <filesets>
                                <fileset>
                                    <directory>src/main/resources/static</directory>
                                </fileset>
                            </filesets>
                        </configuration>
                    </plugin>
                    <plugin>
                        <artifactId>maven-resources-plugin</artifactId>
                        <executions>
                            <execution>
                                <id>copy ui frontend content</id>
                                <phase>generate-resources</phase>
                                <goals>
                                    <goal>copy-resources</goal>
                                </goals>
                                <configuration>
                                    <outputDirectory>src/main/resources/static</outputDirectory>
                                    <overwrite>true</overwrite>
                                    <resources>
                                        <resource>
                                            <directory>${project.basedir}/../ui/dist</directory>
                                        </resource>
                                    </resources>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>

</project>
