name: Backend

on:
  push:
  pull_request:
    paths-ignore:
      - '**/*.md'

concurrency:
  group: backend-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
#    needs: [ code-style ]
    strategy:
      matrix:
        java: [ '17' ]
        os: [ 'ubuntu-latest' ]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 80
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          cache: 'maven'
      - name: Setup mvnw permissions
        run: chmod +x ./mvnw
      - name: Build distribution tar
        run: >-
          ./mvnw -B install
          -D"maven.test.skip"=true
          -D"checkstyle.skip"=true
          -D"http.keepAlive"=false
          -D"maven.wagon.http.pool"=false
          -D"maven.wagon.http.retryHandler.count"=3
          -D"maven.wagon.httpconnectionManager.ttlSeconds"=120
      - name: List files
        run: ls -al
      - name: Upload to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: application-webadmin/target/*.jar
          target: ${{ secrets.APP_PATH }}/app.jar
      - name: Restart application
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            pkill -f 'java -jar' || true
            nohup java -jar ${{ secrets.APP_PATH }}/app.jar --server.port=${{ secrets.APP_PORT }} > ${{ secrets.APP_PATH }}/app.log 2>&1 &